---
name: "pre-release"

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"

jobs:
  gh_pre_release:
    runs-on: "windows-latest"
    steps:
      - name: Get current date
        id: date
        run: $date = (Get-Date).ToString("yyyyMMdd"); echo "date=$($date)" | Out-File -FilePath $env:GITHUB_ENV

      - name: "Checkout source code"
        uses: "actions/checkout@v3"
        with:
          lfs: true
          fetch-depth: 0
          submodules: true

      - name: "Build lmpnn pymol plugin"
        run: |
          $current_dir = Get-Location
          ls
          echo "$current_dir"
          $script = "$current_dir\distribute\package\windows.ps1"
          echo "$script"
          & "$script"
        shell: pwsh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          prerelease: true
          automatic_release_tag: "v${{ env.date }}-nightly"
          title: "Nightly Build ${{ env.date }}"
          files: "lmpnn-gui-pymol-*.zip"

